### PR TITLE
chore: run unauthenticated fetch before authenticated

### LINKED ISSUE #126: Website does not work with DBpedia fragments after login to Solid authentication
This is because after logging in; we *all* fetch calls we make are authenticated fetch calls. When really we should only be making authenticated fetch calls to authenticated endpoints.

Instead what fetch needs to do is try unauthenticated fetch, and on 401 figure out what to do (i.e. should it try with authenticated fetch).

We were just encountering this issue on comunica.dev - not sure if this is a new bug since https://github.com/comunica/comunica/pull/1056/files

### PR DESCRIPTION
**Pull request by jeswr**
closes #126

### CODE REVIEW

**Comment by jeswr** [comment]
@zwifi can you review this quickly

**Review by NSeydoux — APPROVED** [review]

**Review by rubensworks — CHANGES_REQUESTED** [review]
I'm not sure this is actually the fix we really want.

The problem with this solution is that we can increase the number of HTTP requests per query two-fold. Especially in cases where we're doing link traversal, where the number of requests can go in the order of thousands, this will become a significant bottleneck, as query execution will basically take twice as long in some cases.

Alternatively, we could have a (non-default) option in the web client that enables this fallback-based fetch implementation. This would ensure that the general case still performs as fast as possible, and only those queries that require this specific workaround can make use of this mode.

In any case, I think this issue is broader than just the web client here, and should eventually be tackled on a higher level.

**Comment by jeswr** [comment]
> I'm not sure this is actually the fix we really want. | In any case, I think this issue is broader than just the web client here, and should eventually be tackled on a higher level.

@NSeydoux - correct me if I'm wrong; but won't this become the default logic of the Inrupt libraries in a few months anyway?

> Especially in cases where we're doing link traversal, where the number of requests can go in the order of thousands

I see your point here; does it make sense to then use a caching mechanism like

```ts
```

**Comment by rubensworks** [comment]
Good idea, I think this namespace/origin-based caching should solve all major performance issues that could arise from this mechanism. And this could then become the default indeed.

I'm not sure yet though what you have in mind exactly for this `getNamespace` implementation. Just removing the path of the URL?

**Comment by NSeydoux** [comment]
The next version of `solid-client-authn` will indeed rely on a similar logic (defaulting to unauthenticated fetch, and only authenticating if necessary), because preemptive authentication is causing all sorts of issues, in addition of requiring the client to make a guess about the authentication mechanism, which should be discovered from the resource server.

However, you are absolutely right, it would not be acceptable to issue twice as much requests, and optimizations such as the caching @jeswr proposed will be required.

**Comment by jeswr** [comment]
My stance is that we should be caching by namespace rather than origin, i.e. `http://example.org/path?query=1` goes to `http://example.org/path` rather than `http://example.org/`

This could be implemented as
```ts
function getNamespace(input) {
  const url = new URL(new Request(input).url);
  return url.origin + url.pathname;
}
```

**Comment by jeswr** [comment]
@rubensworks  I've added the caching optimisations now. Still won't be as optimal as you want for link traversal to different paths within the same Pod. However, the auth requirements for each of those files *does* need to be checked independentally as they will have different permissions.

In the future I guess we can use Pod metadata to optimise this.

**Comment by rubensworks** [comment]
> My stance is that we should be caching by namespace rather than origin, i.e. http://example.org/path?query=1 goes to http://example.org/path rather than http://example.org/

But in that case we still suffer from the performance problems, right?

For example, when traversing over a pod with 100 Turtle files in `http://example.org/container/`, this would require 200 HTTP requests (instead of 100).

So perhaps origin-based caching may be better after all?

> However, the auth requirements for each of those files does need to be checked independentally as they will have different permissions.

If I'm correct, using authenticated fetch is never a problem on pods, right? I've successfully done authenticated queries over pods with public resources in the past.
So the false-positives in that case may not be a problem.

In any case, a way to disable this behaviour seems important.

> In the future I guess we can use Pod metadata to optimise this.

Definitely, but we just have to be sure that we don't break existing solutions in order to fix other problems :-)

**Comment by jeswr** [comment]
> If I'm correct, using authenticated fetch is never a problem on pods, right?

I have a hunch that this is implementation dependent - and it just so happens that our current implementations are ok with it. But that is more of a questions for someone like @NSeydoux .

> In any case, a way to disable this behaviour seems important.

Agreed - I think we were just in disagreance on which should be the default. I can add in that option here & to the website once we make a decision on whether this is the correct caching strategy for us right now.

**Comment by rubensworks** [comment]
Any updates on this?

**Pull request closed without merging**
