### PR TITLE
#129: Run node as non-root user

### LINKED ISSUE #129: Run container as Non-root User
By default, Docker runs commands inside the container as root which violates the [Principle of Least Privilege (PoLP)](https://en.wikipedia.org/wiki/Principle_of_least_privilege) when superuser permissions are not strictly required. You want to run the container as an unprivileged user whenever possible. The node images provide the node user for such purpose.

https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user

### PR DESCRIPTION
**Pull request by MPParsley**
Fixes #129.

Still requires nginx to run as non-root. See https://www.rockyourcode.com/run-docker-nginx-as-non-root-user/

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks for this @MPParsley!

Since the CI here doesn't build the Dockerfile, can you confirm that it builds+runs ok on your end?

**Comment by MPParsley** [comment]
@rubensworks, added the nginx user. This required to remove the user statement from the default nginx config so it has been added here as well.

```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
```
This allows further configuration of nginx.

Alternatively, we could strip it out from the default config:
```
RUN tail -n +2 /etc/nginx/nginx.conf
```

**Comment by MPParsley** [comment]
@rubensworks, opened a PR with the other approach in #131. Both have been tested.

**Comment by rubensworks** [comment]
Thanks so much for this @MPParsley!

**Pull request merged**
