### PR TITLE
Use YASQE as SPARQL query editor

### PR DESCRIPTION
**Pull request by rubensworks**
As suggested in #8, this enables the YASQE query editor for SPARQL queries.

This does increase the main UI asset size from 239 KB to 709 KB, which is above webpack recommended asset limit of 244 KB. This means that people on slow machines/internet connections might have to wait a bit before they can start querying.

@RubenVerborgh Do you think this ^ is a blocker ?

@joachimvh Can you try breaking it? :-)

### CODE REVIEW

**Comment by joachimvh** [comment]
Regarding the size, maybe we can release multiple versions somehow or would that be too much overhead to keep them consistent?

**Comment by rubensworks** [comment]
> too much overhead to keep them consistent

Yes, overhead would be a bit too high in the current form of this widget.

**Comment by joachimvh** [comment]
Things I could find so far:

 * When going to the client the SPARQL field is empty whereas it used to contain a query (the first one in the list of queries).
 * Not sure whether something can be changed about this, but when I add a newline in a query the indentation starts at the wrong level.
 * The expand button in the top right overlaps with the scrollbar.

**Comment by RubenVerborgh** [comment]
> Yes, overhead would be a bit too high in the current form of this widget.

Given that you've only needed to add code (not remove or change), an `if (yasqe)` should be sufficient.

**Comment by RubenVerborgh** [comment]
> @RubenVerborgh Do you think this ^ is a blocker ?

Not at all, good stuff!

**Comment by rubensworks** [comment]
> When going to the client the SPARQL field is empty whereas it used to contain a query (the first one in the list of queries).

Ah, that's because YASQE does some internal caching. I'll see what I can do.

> * Not sure whether something can be changed about this, but when I add a newline in a query the indentation starts at the wrong level.
* The expand button in the top right overlaps with the scrollbar.

I think these are issues in YASQE itself.

**Pull request merged**
